name: Deploy storybook web preview
on: pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and build storybook
        run: 'npm ci && npm run build:storybook'
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@ff6e7dde58a4f7f1db590927596bf683250c6cc8
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB_APP_TEMPLATE_1BD48 }}'
          projectId: web-app-template-1bd48
          channelId: 'staging-${{github.event.pull_request.number}}'
          expires: 7d
