name: 'Jest coverage report'

on: [pull_request]

jobs:
  jest_coverage_report:
    name: 'Jest coverage report'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: Coverage PR comment
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
